Repository JapaneseEducateService/frontend, pull requests merged in 2024-04, with the labels that each got.

#42 🐞 BugFix : flipcard
  src/css/FlipWordPage.module.css
  src/img/flipcard.png
  src/views/CallBack.tsx
  src/views/FlipWordPage.tsx
  src/views/SignInPage.tsx
Labels: 🐞 BugFix

#44 🐞 BugFix : login fix
  src/css/SignIn.module.css
  src/img/socialgithub.png
  src/img/socialgoogle.png
  src/img/socialkakao.png
  src/img/socialnaver.png
  src/views/SignInPage.tsx
Labels: 🐞 BugFix

#45 🐞 BugFix : bugfix
  package-lock.json
  package.json
  src/api/axios.ts
  src/api/typing.ts
  src/constants/typing.ts
  src/css/SignIn.module.css
  src/css/SignUp.module.css
  src/css/Typing.module.css
  src/views/FlipWordPage.tsx
  src/views/SignInPage.tsx
  src/views/SignUpPage.tsx
  src/views/TypingPage.tsx
Labels: 🐞 BugFix

#46 🔨 Refactor :fix
  src/api/typingetuser.ts
  src/api/typinguser.ts
  src/components/UserTypingUpload.tsx
  src/css/Typing.module.css
  src/css/UserTypingUpload.module.css
  src/views/TypingPage.tsx
Labels: 🔨 Refactor

#48 ✨ feat : Build PronunciationPage, Fix few pages( * Do npm i )
  package-lock.json
  package.json
  src/App.tsx
  src/components/LoadingBar.tsx
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/components/game/assets/js/FoggyStageScene.tsx
  src/components/game/assets/js/StageScene.tsx
  src/components/game/assets/js/config.tsx
  src/css/GamePage.module.css
  src/css/LoadingBar.module.css
  src/css/PronunciationPage.module.css
  src/css/WordCardPage.module.css
  src/views/GamePage.tsx
  src/views/GrammerPage.tsx
  src/views/PronunciationPage.tsx
Labels: ✨ Feature

#49 ✨ feat : FIx pronunciation page for change to wav format ( DO npm install )
  package-lock.json
  package.json
  src/views/PronunciationPage.tsx
Labels: 🐞 BugFix

#50 ✨ feat : Fix pronunciation Page, setListPage add adminSets
  src/views/GrammerPage.tsx
  src/views/PronunciationPage.tsx
  src/views/SetListPage.tsx
Labels: 🐞 BugFix

#51 🐞 BugFix : 버그 픽스에 대한 커밋
  src/css/FlipWordPage.module.css
  src/views/FlipWordPage.tsx
Labels: 🐞 BugFix
