Repository JapaneseEducateService/frontend, pull requests merged in 2024-03, with the labels that each got.

#21 ✨ feat : social login, login 수정
  package.json
  src/App.tsx
  src/css/SignIn.module.css
  src/img/socialgithub.png
  src/img/socialgoogle.png
  src/img/socialkakao.png
  src/img/socialnaver.png
  src/views/CallBack.tsx
  src/views/SignInPage.tsx
  src/views/SignUpPage.tsx
Labels: ✨ Feature

#22 ✨ feat : Nav bar components fix
  src/views/GamePage.tsx
  src/views/MainPage.tsx
  src/views/SignInPage.tsx
  src/views/SignUpPage.tsx
Labels: 🐞 BugFix

#23 ✨ feat: Implement login state management using Context API and add lo…
  src/App.tsx
  src/components/Navbar.tsx
  src/contexts/AuthContext.tsx
  src/css/nav.module.css
Labels: ✨ Feature

#25 ✨ feat : Implement axios module And add CreateWordPage (* DO npm inst…
  package-lock.json
  package.json
  src/App.tsx
  src/api/axios.ts
  src/api/requests.ts
  src/components/Navbar.tsx
  src/css/CreateWordPage.module.css
  src/views/CreateWordPage.tsx
Labels: ✨ Feature

#29 ✨ feat : Add font, Build drog&drop in createWordPage
  src/App.css
  src/components/Modal.tsx
  src/css/CreateWordPage.module.css
  src/css/modal.module.css
  src/index.css
  src/views/CallBack.tsx
  src/views/CreateWordPage.tsx
Labels: ✨ Feature

#30 ✨ feat : Fixed game bug, Add responsive desgin, Modify Navbar desgin
  src/api/axios.ts
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/components/crarousel/css/embla.css
  src/components/game/assets/js/FoggyStageScene.tsx
  src/css/CreateWordPage.module.css
  src/css/Main.module.css
  src/css/nav.module.css
  src/img/tamago_logo.png
  src/index.css
  src/views/MainPage.tsx
Labels: ✨ Feature

#31 ✨ feat : Add Loading Component.createWordPage logic.( * Do npm Install )
  package-lock.json
  package.json
  src/App.tsx
  src/components/LoadingBar.tsx
  src/components/Modal.tsx
  src/contexts/DataContext.tsx
  src/css/CreateWordPage.module.css
  src/css/modal.module.css
  src/views/CreateWordPage.tsx
Labels: ✨ Feature

#32 ✨ feat : Fix createWordPage bug
  src/contexts/DataContext.tsx
  src/css/CreateWordPage.module.css
  src/views/CreateWordPage.tsx
Labels: 🐞 BugFix

#33 🐞 BugFix：typingbug
  src/css/Typing.module.css
  src/views/TypingPage.tsx
Labels: 🐞 BugFix

#34 ✨ feat : Build SetListPage, WordCardPage etc...
  src/App.tsx
  src/api/axios.ts
  src/components/LoadingBar.tsx
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/css/CreateWordPage.module.css
  src/css/LoadingBar.module.css
  src/css/SetListpage.module.css
  src/css/WordCardPage.module.css
  src/css/modal.module.css
  src/css/nav.module.css
  src/views/CreateWordPage.tsx
  src/views/SetListPage.tsx
  src/views/WordCardPage.tsx
Labels: ✨ Feature

#36 ✨ feat : Fix NavBar to Link for SPA & Change font color Modal
  src/components/Navbar.tsx
  src/css/CreateWordPage.module.css
  src/css/modal.module.css
  src/css/nav.module.css
Labels: 🥰 Accessibility

#37 ✨ feat : Build SetList Page, WordCardPage, Memorize Page, and Add fra…
  package-lock.json
  package.json
  src/App.tsx
  src/components/Modal.tsx
  src/components/NavbarController.tsx
  src/css/MemorizePage.module.css
  src/css/SetListpage.module.css
  src/css/WordCardPage.module.css
  src/views/Memorizepage.tsx
  src/views/SetListPage.tsx
  src/views/WordCardPage.tsx
Labels: ✨ Feature

#38 🐞 BugFix: bug fix
  src/css/FlipWordPage.module.css
  src/views/FlipWordPage.tsx
  src/views/TypingPage.tsx
Labels: 🐞 BugFix

#39 ✨ feat : Fix Memorize Page
  src/css/MemorizePage.module.css
  src/views/Memorizepage.tsx
Labels: ✨ Feature

#40 ✨ feat : fix bug
  src/css/MemorizePage.module.css
  src/views/CreateWordPage.tsx
  src/views/Memorizepage.tsx
  src/views/SetListPage.tsx
  src/views/SignInPage.tsx
Labels: 🐞 BugFix

#41 ✨ feat : Add End func to Memorize Page
  src/css/MemorizePage.module.css
  src/views/Memorizepage.tsx
Labels: ✨ Feature
